# ========================================
# MarryCore - Configuración de Base de Datos
# Autor: Brocolitx
# Versión: 0.0.1
# ========================================

database:
  # Configuración del servidor MySQL
  host: "localhost"
  port: 3306
  name: "marrycore"

  # Credenciales de acceso
  # IMPORTANTE: Cambia estos valores por los correctos
  username: "root"  # o "root" si usas el usuario root
  password: "tu_contraseña"   # pon aquí tu contraseña real

  # Configuraciones adicionales
  useSSL: false
  autoReconnect: true

  # Configuraciones de conexión avanzadas (opcionales)
  # maxConnections: 10
  # connectionTimeout: 30000
  # maxLifetime: 1800000

# ========================================
# Instrucciones de configuración:
# ========================================
# 1. Asegúrate de que MySQL esté ejecutándose
# 2. Crea la base de datos 'marrycore' si no existe
# 3. Configura las credenciales correctas arriba
# 4. Si usas un servidor remoto, cambia 'localhost' por la IP
# 5. Guarda el archivo y reinicia el servidor

# ========================================
# Comandos SQL para configurar la base de datos:
# ========================================
# CREATE DATABASE IF NOT EXISTS marrycore
# CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
#
# CREATE USER IF NOT EXISTS 'marrycore_user'@'localhost'
# IDENTIFIED BY 'tu_contraseña';
#
# GRANT ALL PRIVILEGES ON marrycore.*
# TO 'marrycore_user'@'localhost';
#
# FLUSH PRIVILEGES;