name: MarryCore
version: '0.0.1'
main: gc.grivyzom.marryCore.MarryCore
api-version: '1.20'
authors: [ Brocolitx ]
website: www.grivyzom.com
description: Sistema completo de matrimonio para servidores de Minecraft Survival
softdepend: [PlaceholderAPI, LuckPerms, Vault, WorldGuard]

commands:
  marry:
    description: Comando principal para el sistema de matrimonio
    aliases: [casarse, matrimonio]
    usage: /marry <jugador> - Proponer matrimonio a un jugador
    permission: marrycore.marry
    permission-message: §cNo tienes permisos para usar este comando.

  aceptar:
    description: Aceptar propuesta de matrimonio
    aliases: [accept, si, yes]
    usage: /aceptar - Aceptar propuesta de matrimonio pendiente
    permission: marrycore.marry
    permission-message: §cNo tienes permisos para usar este comando.

  rechazar:
    description: Rechazar propuesta de matrimonio
    aliases: [reject, no]
    usage: /rechazar - Rechazar propuesta de matrimonio pendiente
    permission: marrycore.marry
    permission-message: §cNo tienes permisos para usar este comando.

  casamiento:
    description: Programar fecha de casamiento
    aliases: [boda, wedding]
    usage: /casamiento <fecha> [hora] - Programar ceremonia de matrimonio
    permission: marrycore.wedding
    permission-message: §cNo tienes permisos para usar este comando.

  invitados:
    description: Gestionar invitados para la ceremonia
    aliases: [guests, invitar]
    usage: /invitados <add|remove|list> [jugador] - Gestionar lista de invitados
    permission: marrycore.guests
    permission-message: §cNo tienes permisos para usar este comando.

  divorcio:
    description: Divorciarse de la pareja actual
    aliases: [divorce, separarse]
    usage: /divorcio - Divorciarse de la pareja actual
    permission: marrycore.divorce
    permission-message: §cNo tienes permisos para usar este comando.

  conyuge:
    description: Teletransportarse al cónyuge
    aliases: [spouse, tp, pareja]
    usage: /conyuge - Teletransportarse al cónyuge
    permission: marrycore.teleport
    permission-message: §cNo tienes permisos para usar este comando.

  marrycore:
    description: Comandos administrativos del sistema de matrimonio
    aliases: [mc, marrycoreadmin]
    usage: /marrycore <subcomando> - Administración del plugin
    permission: marrycore.admin
    permission-message: §cNo tienes permisos para usar este comando.

permissions:
  marrycore.*:
    description: Acceso completo a todas las funciones de MarryCore
    default: op
    children:
      marrycore.marry: true
      marrycore.wedding: true
      marrycore.guests: true
      marrycore.divorce: true
      marrycore.teleport: true
      marrycore.admin: true
      marrycore.bypass: true

  marrycore.marry:
    description: Permite proponer matrimonio y aceptar/rechazar propuestas
    default: true

  marrycore.wedding:
    description: Permite programar ceremonias de matrimonio
    default: true

  marrycore.guests:
    description: Permite gestionar invitados a ceremonias
    default: true

  marrycore.divorce:
    description: Permite divorciarse de la pareja actual
    default: true

  marrycore.teleport:
    description: Permite teletransportarse al cónyuge
    default: true

  marrycore.admin:
    description: Comandos administrativos del sistema de matrimonio
    default: op
    children:
      marrycore.admin.reload: true
      marrycore.admin.force: true
      marrycore.admin.give: true
      marrycore.admin.reset: true
      marrycore.admin.stats: true
      marrycore.admin.repair: true

  marrycore.admin.reload:
    description: Permite recargar la configuración del plugin
    default: op

  marrycore.admin.force:
    description: Permite forzar matrimonios y divorcios
    default: op

  marrycore.admin.give:
    description: Permite dar ítems especiales a jugadores
    default: op

  marrycore.admin.reset:
    description: Permite resetear datos de matrimonio de jugadores
    default: op

  marrycore.admin.stats:
    description: Permite ver estadísticas del sistema
    default: op

  marrycore.admin.repair:
    description: Permite reparar la base de datos
    default: op

  marrycore.bypass:
    description: Permite saltarse restricciones como cooldowns y límites
    default: op
    children:
      marrycore.bypass.cooldown: true
      marrycore.bypass.distance: true
      marrycore.bypass.limits: true

  marrycore.bypass.cooldown:
    description: Permite saltarse cooldowns de teletransporte
    default: op

  marrycore.bypass.distance:
    description: Permite proponer matrimonio sin restricción de distancia
    default: op

  marrycore.bypass.limits:
    description: Permite saltarse límites de propuestas diarias
    default: op

  marrycore.craft:
    description: Permite craftear ítems especiales del matrimonio
    default: true

  marrycore.craft.rings:
    description: Permite craftear anillos de propuesta
    default: true

  marrycore.benefits:
    description: Acceso a beneficios del matrimonio
    default: true
    children:
      marrycore.benefits.experience: true
      marrycore.benefits.chat: true
      marrycore.benefits.missions: true

  marrycore.benefits.experience:
    description: Permite recibir bonus de experiencia por estar casado
    default: true

  marrycore.benefits.chat:
    description: Permite usar el chat privado entre cónyuges
    default: true

  marrycore.benefits.missions:
    description: Permite acceder a misiones diarias de pareja
    default: true

  marrycore.notify:
    description: Permite recibir notificaciones del sistema
    default: true

  marrycore.notify.proposals:
    description: Permite recibir notificaciones de propuestas
    default: true

  marrycore.notify.weddings:
    description: Permite recibir notificaciones de bodas
    default: true

  marrycore.notify.divorces:
    description: Permite recibir notificaciones de divorcios
    default: true